# Generated by Django 4.2.7 on 2026-03-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='district',
            field=models.CharField(blank=True, max_length=120, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='cart',
            name='province',
            field=models.CharField(blank=True, max_length=120, verbose_name='Tỉnh/Thành'),
        ),
        migrations.AddField(
            model_name='cart',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='ward',
            field=models.CharField(blank=True, max_length=120, verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ (số nhà, đường)'),
        ),
    ]
