from django.urls import path

from . import views

app_name = "api"

urlpatterns = [
    path("login", views.react_login_api, name="react_login"),
    path("logout", views.react_logout_api, name="react_logout"),
    path("register", views.react_register_api, name="react_register"),
    path("auth", views.react_me_api, name="react_me"),
    path("payments", views.react_payments_api, name="react_payments"),
    path("payment", views.react_payment_api, name="react_payment"),
    path("paymentcod", views.react_payment_cod_api, name="react_payment_cod"),
    path("paymentvnpay", views.react_payment_vnpay_api, name="react_payment_vnpay"),
    path("update-info-cart", views.react_update_info_cart_api, name="react_update_info_cart"),
    path("product", views.product_query_legacy_api, name="product_query_legacy"),
    path("similarproduct", views.similar_product_legacy_api, name="similar_product_legacy"),
    path("search", views.search_legacy_api, name="search_legacy"),
    path("addtocart", views.react_addtocart_api, name="react_addtocart"),
    path("deletecart", views.react_deletecart_api, name="react_deletecart"),
    path("update-product", views.react_update_product_api, name="react_update_product"),
    path("health", views.health_api, name="health"),
    path("recommendations", views.recommendations_api, name="recommendations"),
    path("chat", views.chat_api, name="chat"),
    path("auth/register", views.RegisterApiView.as_view(), name="auth_register"),
    path("auth/login", views.LoginApiView.as_view(), name="auth_login"),
    path("auth/refresh", views.RefreshApiView.as_view(), name="auth_refresh"),
    path("auth/me", views.MeApiView.as_view(), name="auth_me"),
    path("auth/change-password", views.ChangePasswordApiView.as_view(), name="auth_change_password"),
    path("auth/forgot-password", views.ForgotPasswordApiView.as_view(), name="auth_forgot_password"),
    path("auth/reset-password", views.ResetPasswordApiView.as_view(), name="auth_reset_password"),
    path("products", views.products_api, name="products"),
    path("products/<int:pk>", views.product_detail_api, name="product_detail"),
    path("cart", views.cart_api, name="cart"),
    path("cart/voucher/apply", views.react_apply_voucher_api, name="cart_voucher_apply"),
    path("cart/voucher/remove", views.react_remove_voucher_api, name="cart_voucher_remove"),
    path("cart/add", views.cart_add_api, name="cart_add"),
    path("cart/<int:item_id>", views.cart_update_api, name="cart_update"),
    path("cart/<int:item_id>/delete", views.cart_delete_api, name="cart_delete"),
    path("cart/clear", views.cart_clear_api, name="cart_clear"),
    path("orders", views.order_list_api, name="orders"),
    path("orders/create", views.order_create_api, name="order_create"),
    path("orders/<int:order_id>", views.order_detail_api, name="order_detail"),
    path("orders/<int:order_id>/cancel", views.order_cancel_api, name="order_cancel"),
    path("payments/cod", views.payment_cod_api, name="payment_cod"),
    path("payments/vnpay", views.payment_vnpay_api, name="payment_vnpay"),
    path("payments/momo", views.payment_momo_api, name="payment_momo"),
    path("payments/vnpay/callback", views.payment_vnpay_callback_api, name="payment_vnpay_callback"),
    path("payments/momo/callback", views.payment_momo_callback_api, name="payment_momo_callback"),
]
